### ISSUE TITLE
Reviving sbt-pit Plugin

### ISSUE THREAD

**Issue by iadcode** [pitest/sbt-pit#1]
I am a user of sbt and I am starting to implement pitest for my projects. This plugin seems like the natural go to point.
Can I ask what would be involve in reviving this plugin?

At the moment I have a version of the plugin forked on my own repository, which I manually deployed to and use from my private package repository. This code has been rewritten compatible for:
sbt version 1.3.13
pitest version 1.6.3
scala version cross compatible for 2.10.7, 2.11.12, 2.12.13

https://github.com/iadcode/sbt-pit

This does not have any testing and not exacly a long term plan.

Do you think there would be enough interest to get this going again?

**Comment by hcoles** [comment]
I don't think there would be much interest in an sbt plugin. Pitest isn't really usable for scala, and the number of people using sbt to build java or kotlin must be vanishingly small.

It sounds like you've done all the work to get it going with a more uptodate sbt however. You'd be welcome to host that here as an 'official' sbt-pit if you wish. I should be able to get it synced to maven central, but you would likely still be the sole maintainer.

**Comment by iadcode** [comment]
Thank you for your prompt reply. I had a feeling that will be the case. I will think more on this matter and if and when I've made my decision, I will make the pull request. Will close this issue for now. Thanks again, @hcoles.
